USE LIGHTADVENTUREWORKSDW
GO

IF OBJECT_ID('dbo.SeqCustomerDwKey','SO') IS NOT NULL
    DROP SEQUENCE dbo.SeqCustomerDwKey
GO

CREATE SEQUENCE dbo.SeqCustomerDwKey AS INT 
    START WITH 1 
    INCREMENT BY 1
GO